### PR TITLE
Get secrets from .env

### PR DESCRIPTION
**Pull request by BartekGG**
It's easier to store token in .env file.

### CODE REVIEW

**Comment by BartekGG** [comment]
@mickac @Jan-Sk can you have a look?

**Comment by mickac** [comment]
Great method to keep enviromental variables for security reason, great work @BartekGG

**Comment by Jan-Sk** [comment]
maybe create something like gitignore

**Review by Mieszko96 — APPROVED** [review]

**Review by Jan-Sk — APPROVED** [review]

**Review by mickac — APPROVED** [review]

**Comment by BartekGG** [comment]
> maybe create something like gitignore to remove modules from repo...

Modules were removed in different pull request.

**Pull request merged**
